### ISSUE TITLE
Exception when calling Add Migration with a shortcut

### ISSUE THREAD

**Issue by MelnikovVA** [seclerp/rider-efcore#52] opened 2022-02-01 03:33 UTC
Hello! Just discovered your plugin and wanted to give it a try. Everything's working fine when I manually open the project Tools section and click on the "Add Migration" option. However, a much more convenient approach for me would be to call the command with a shortcut, so I assigned one to the "Add Migration" option in Rider's Keymap section. However, after trying to call the command with a shortcut, I'm getting a null pointer exception: 
![Screenshot_2](https://user-images.githubusercontent.com/51045785/151908809-9a83f304-026c-4cf2-90c5-4c8181c6b8cd.png)

In case this is not a bug related to the plugin, is there a way to trigger the plugin's commands by using a shortcut? Opening the explorer window, finding the project, rightclicking it and going through several context menus before reaching the command is a little too much hassle when one could simply open the same tab with a couple key strokes.😅

**Comment by seclerp** [comment] 2022-02-01 03:57
Hi Vladimir, thanks for trying plugin and for the feedback!

The root cause of this error is the design of all commands of this plugin - they depend on specific project. The reason why you need to go through the context menu levels is that action needs to be run on the project file, that's why detached action execution is not possible at that moment.

But I also think that from UX point of view it's not so handy to have such long journey to all commands every time. I think in next releases I will add alternative way of executing such commands without relying on project file, it will be quite important improvement so it will be in my first priorities.

After that change you will be able to customize action execution in the way you want :)

**Comment by seclerp** [comment] 2022-02-01 04:06
Little background about why it was made like that initially:

We have "preferred projects" feature. It allows you to set and persist project pairs (Migrations + Startup). When you execute action for some project pair at first time selected project are persisted for further execution.

You could have different project pairs in your solution and they will never overlap using such an approach.

Here comes the selected project file - we determine which project is selected and which project pair should be used for current action execution.

**Comment by MelnikovVA** [comment] 2022-02-01 06:25
Got you, thanks, will be waiting for the update!

**Closed** 2022-02-01 11:04 UTC

**Comment by seclerp** [comment] 2022-02-01 22:39
@MelnikovVA feature is on the way:

![image](https://user-images.githubusercontent.com/20597871/152063348-ea4b56f5-3516-4afb-878f-495bd02d2d47.png)

It will be also possible to bind shortcut to open a new Quick Actions popup (just like VCS Operations):

![image](https://user-images.githubusercontent.com/20597871/152063404-0cbeb127-ea4e-41fb-bbb5-714f20217a5d.png)

Of course, you will be able to bind on specific actions too.

**Comment by MelnikovVA** [comment] 2022-02-02 06:47
Awesome!😄
