### ISSUE TITLE
DbContext class not showing up

### ISSUE THREAD

**Issue by caffreysbb** [seclerp/rider-efcore#105] opened 2022-08-12 13:57 UTC
DataAccess project
```
    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.8" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.8" />
      <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="6.0.8" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    </ItemGroup>
```

Startup Project:
```
    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.8" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.8">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.2.3" />
    </ItemGroup>
```

![изображение](https://user-images.githubusercontent.com/59992069/184368629-f1579fde-3d20-41e7-88ad-a03c10256cd2.png)
![изображение](https://user-images.githubusercontent.com/59992069/184368383-7dc1cea3-dd67-4fb2-ae3c-705ae497e90a.png)

- OS: Win10
- .NET SDK info (installed ones and version used within Rider): Net. 6
- Plugin version: latest
- Rider version: latest

**Comment by seclerp** [comment] 2022-08-12 15:01
Please be more specific with what you mean by  "latest" versions.

Which shape your DbContext class is? Could you show me the class header (name, ineritance, attributes)

**Comment by caffreysbb** [comment] 2022-08-12 15:03
> 

Rider 2022.2.1
Plugin 222.1.0

`public class ApplicationDbContext : IdentityDbContext<User>
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options)
        { 
           //  Database.EnsureDeleted();
           //  Database.EnsureCreated();
        }`

**Comment by seclerp** [comment] 2022-08-12 15:19
I can't reproduce your issue. Do you have build errors when opening the dialog? 

If not, it will be great if you provide a minimal repro .NET solution.

**Comment by caffreysbb** [comment] 2022-08-12 15:40
Magic! =)
I create new project and copy paste code.

![изображение](https://user-images.githubusercontent.com/59992069/184391119-72c0c644-5c1a-455e-8f64-ae7dae4b55c0.png)

**Comment by caffreysbb** [comment] 2022-08-12 16:19
if disable Nullable reference in project - again not working

**Comment by caffreysbb** [comment] 2022-08-13 05:42
if i remove not working project and rename test project whatewer not show context.
if in test project disable nullable reference in project settings - not show context or not show startup project

**Comment by seclerp** [comment] 2022-08-15 12:51
I can reproduce maybe related issue and will look into it, but it's related to the Startup project, not DbContext

**Comment by Jammyo** [comment] 2022-09-01 10:02
I have a similar issue, but I can't see from the screenshot whether it's exactly the same issue. I can pin it down to a specific set of circumstances by:

1. Creating a new solution.
2. Creating a solution folder (I named it Test)
3. Creating a project inside the solution folder with the same name (Test again).
4. Create a class and make it implement DbContext.
5. Try to add a migration
6. DbContext list is empty.

To get the dialog to recognise the DbContext, I can rename the project to anything (Test2 for example), and the dialog now picks up the db context.

I had a browse through what looks like the relevant bit of code ([dbContextProvider.GetDbContexts](https://github.com/seclerp/rider-efcore/blob/4d1e4ed9aa3680d6e2ff144443dfc086d50b56f1/src/dotnet/Rider.Plugins.EfCore/DbContext/DbContextProvider.cs#L16), but it looks super clear that it should be working. I wonder if this could be a Jetbrains bug, although I had a quick browse through youtrack and didn't see immediately anything obviously related.

**Comment by seclerp** [comment] 2022-09-01 17:58
@Jammyo did your tried the `222.1.1` version of a plugin?

**Comment by Jammyo** [comment] 2022-09-05 15:48
Hi @seclerp , yes I'm using the latest version. I've attached a sample solution for you to test. I'm more and more convinced that this is a Rider bug, because I did manage to get it to work sometimes after renaming both the solution folder and the project, however this only worked if I renamed the project, then the solution folder. The other way round changed nothing, and restarting Rider loses this 'fix'.
[Test.zip](https://github.com/seclerp/rider-efcore/files/9491035/Test.zip)

**Comment by seclerp** [comment] 2022-09-05 15:54
Do you have your project listed when `DbContext` is not shown? Or both project and context are not visible in dropdowns sometimes?

Could you also send your logs? Right after you reproduce the issue.

**Comment by Jammyo** [comment] 2022-09-05 17:28
The project is listed, just the DbContext is missing. I've attached what looks like the relevant logs. 
To collect, I
- Opened from fresh.
- Tried to add a migration to the test project.
- Renamed the solution folder.
- Renamed the project folder.
- Tried again.

It looks like there was an error thrown on solution loaded. 

[22804.backend.zip](https://github.com/seclerp/rider-efcore/files/9491408/22804.backend.zip)

**Comment by seclerp** [comment] 2022-09-05 17:29
Thanks! `idea.log` file is also mandatory in this case.

**Comment by Jammyo** [comment] 2022-09-05 18:09
[idea.log](https://github.com/seclerp/rider-efcore/files/9491548/idea.log)
Ah, sorry. Here you go. :)

**Comment by seclerp** [comment] 2022-09-05 19:16
Thanks a lot for the logs and reproducible solution! I am also able to reproduce it in the scope of different project.

> It looks like there was an error thrown on solution loaded.

You're correct. On the line below:
```csharp
var efToolsDefinitionValue = _efCoreModel.EfToolsDefinition.Value;
if (efToolsDefinitionValue != null)
{
  CheckToolsInstalled(efToolsDefinitionValue);
}
```
We are trying to get `EfToolsDefinition` value that is not initialized at that moment. The value should be available right after the first `NuGetDotnetToolsTracker.Change` is fired. But, as we can see, it could happen after the solution load task.

What we could do is skip the `EfToolsDefinition` check on startup if a value is not presented yet:
```csharp
if (_efCoreModel.EfToolsDefinition.Maybe.HasValue)
{
  var efToolsDefinitionValue = _efCoreModel.EfToolsDefinition.Value;
  if (efToolsDefinitionValue != null)
  {
    CheckToolsInstalled(efToolsDefinitionValue);
  }
}
```

I'm quite busy with other stuff right now so if you want to help with implementation I will be very appreciated! 😃

**Comment by seclerp** [comment] 2022-09-05 19:22
Even if we found this potential root cause, I'm not really sure that this could be the reason for the bug. We are receiving the DbContext list on demand when opening any dialog or changing the currently selected Migrations project, there is nothing related to the solution startup. So it needs further investigation.

**Comment by seclerp** [comment] 2022-09-09 14:32
Hey @Jammyo, great news - I found the exact reason why it's behaving like that.

It's because from the beginning of this project we are using project names as a "unique project identifier" but it was too naive as what we see from version to version. In your particular case "Test" solution folder shadows "Test" project because it comes first in a list of "projects" (`ProjectModelItems` to be precise) with such name. I think the issue will also be reproducible if you have projects with the same name but in different physical locations.

I'll make adjustments to use a project's GUID as an identifier in internal sources, but it will be only available from the next major release of the plugin (it's because of huge changes in a codebase in a refactoring branch).

BTW a little issue with the startup exception from above is already fixed in the release branch.

**Closed** 2022-12-09 14:43 UTC
Labels: bug, good first issue
